all:
	mex dttrain.cpp decisiontree.cpp treeaccessory.cpp parameters.cpp nodeclassifier.cpp feature.cpp linear.cpp tron.cpp yblas.cpp
	mex dttest.cpp decisiontree.cpp treeaccessory.cpp parameters.cpp nodeclassifier.cpp feature.cpp linear.cpp tron.cpp yblas.cpp
	mex GetSparseDataFunc.cpp
	mex MaxPoolingData.cpp
